# Resets kubernetes after a failed installation
---
- name: Reset kubeadm
  ansible.builtin.command: kubeadm reset --force
  ignore_errors: true # Continue even if reset fails (e.g., already reset)

- name: Remove CNI configuration (if applicable)
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: absent
  ignore_errors: true

- name: Remove kubelet configuration
  ansible.builtin.file:
    path: /var/lib/kubelet
    state: absent
  ignore_errors: true

- name: Remove containerd configuration
  ansible.builtin.file:
    path: /var/lib/containerd
    state: absent
  ignore_errors: true

- name: Remove iptables rules (if applicable)
  ansible.builtin.command: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  ignore_errors: true

- name: Remove ipvs rules (if applicable)
  ansible.builtin.command: ipvsadm -C
  ignore_errors: true

- name: Remove flannel interface (if applicable)
  ansible.builtin.command: ip link delete cni0
  ignore_errors: true

- name: Remove kubernetes related directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - $HOME/.kube

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  ignore_errors: true # container runtime may not be installed.

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
  ignore_errors: true # kubelet may not be installed.
